spring.application.name=coliv-backend

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET:umaChaveSecretaQualquerComMaisDe32CaracteresLocal}
jwt.expiration-ms=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#cloudflare.r2.endpoint=${CF_R2_ENDPOINT}
#cloudflare.r2.access-key=${CF_R2_ACCESS_KEY}
#cloudflare.r2.secret-key=${CF_R2_SECRET_KEY}
#cloudflare.r2.bucket-name=${CF_R2_BUCKET_NAME}
#cloudflare.r2.public-url=${CF_R2_PUBLIC_URL}

cloudflare.r2.endpoint=${CF_R2_ENDPOINT:https://e7314cd28857cb7445a1f4fc43258109.r2.cloudflarestorage.com/coliv-imagens}
cloudflare.r2.access-key=${CF_R2_ACCESS_KEY:8855586e3c04bc3cefe20a489b0619d2}
cloudflare.r2.secret-key=${CF_R2_SECRET_KEY:b245a8b1f1dc2263341cb660dec041462fa2ecd3353e705cca374d86c1c6c4fc}
cloudflare.r2.bucket-name=${CF_R2_BUCKET_NAME:coliv-imagens}
cloudflare.r2.public-url=${CF_R2_PUBLIC_URL:https://pub-5ef84069d56d4372ba1d7685a28f5d27.r2.dev}