spring.application.name=coliv-backend

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET:umaChaveSecretaQualquerComMaisDe32CaracteresLocal}
jwt.expiration-ms=86400000

spring.docker.compose.readiness.wait=never

stomp.relay.host=${STOMP_RELAY_HOST}
stomp.relay.port=${STOMP_RELAY_PORT}
stomp.client.login=${STOMP_CLIENT_LOGIN}
stomp.client.passcode=${STOMP_CLIENT_PASSCODE}
stomp.system.login=${STOMP_SYSTEM_LOGIN}
stomp.system.passcode=${STOMP_SYSTEM_PASSCODE}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudflare.r2.endpoint=${CF_R2_ENDPOINT}
cloudflare.r2.access-key=${CF_R2_ACCESS_KEY}
cloudflare.r2.secret-key=${CF_R2_SECRET_KEY}
cloudflare.r2.bucket-name=${CF_R2_BUCKET_NAME}
cloudflare.r2.public-url=${CF_R2_PUBLIC_URL}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB
#abacatepay.url=${ABACATEPAY_URL}
#abacatepay.api-key=${ABACATEPAY_API_KEY}
#abacatepay.webhook-secret=${ABACATEPAY_WEBHOOK_SECRET}