spring.application.name=coliv-backend

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações do Cloudflare R2
cloudflare.r2.endpoint=${CF_R2_ENDPOINT}
cloudflare.r2.access-key=${CF_R2_ACCESS_KEY}
cloudflare.r2.secret-key=${CF_R2_SECRET_KEY}
cloudflare.r2.bucket-name=${CF_R2_BUCKET_NAME}
cloudflare.r2.public-url=${CF_R2_PUBLIC_URL}